version: '3'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://MATT-XPS:9092'
      KAFKA_ZOOKEEPER_CONNECT: MATT-XPS:2181
  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    ports:
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://MATT-XPS:9093'
      KAFKA_ZOOKEEPER_CONNECT: MATT-XPS:2181
  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    ports:
      - '9094:9094'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://MATT-XPS:9094'
      KAFKA_ZOOKEEPER_CONNECT: MATT-XPS:2181